export const FETCH_ALL_BRANDS = 'FETCH_ALL_BRANDS';
export const FETCH_ALL_BRANDS_SUCCESS = 'FETCH_ALL_BRANDS_SUCCESS';
export const FETCH_ALL_BRANDS_ERROR = 'FETCH_ALL_BRANDS_ERROR';

export const FETCH_ONE_BRAND = 'FETCH_ONE_BRAND';
export const FETCH_ONE_BRAND_SUCCESS = 'FETCH_ONE_BRAND_SUCCESS';
export const FETCH_ONE_BRAND_ERROR = 'FETCH_ONE_BRAND_ERROR';

export const CREATE_BRAND = 'CREATE_BRAND';
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const CREATE_BRAND_ERROR = 'CREATE_BRAND_ERROR';

export const UPDATE_BRAND = 'UPDATE_BRAND';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const UPDATE_BRAND_ERROR = 'UPDATE_BRAND_ERROR';

export const DELETE_BRAND = 'DELETE_BRAND';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_ERROR = 'DELETE_BRAND_ERROR';

export const CLEAR_ONE_BRAND = 'CLEAR_ONE_BRAND';