export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS';
export const FETCH_ALL_ORDERS_ERROR = 'FETCH_ALL_ORDERS_ERROR';

export const FETCH_ONE_ORDER = 'FETCH_ONE_ORDER';
export const FETCH_ONE_ORDER_SUCCESS = 'FETCH_ONE_ORDER_SUCCESS';
export const FETCH_ONE_ORDER_ERROR = 'FETCH_ONE_ORDER_ERROR';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';

export const CLEAR_ONE_ORDER = 'CLEAR_ONE_ORDER';