export const SET_USER_AUTH = 'SET_USER_AUTH';
export const LOGOUT_USER = 'LOGOUT_USER';

export const BUY_PRODUCT = 'BUY_PRODUCT';
export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR';